name: Deploy Website

on:
  push:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir ~/.ssh
      - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: 'echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts'
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: chmod 400 ~/.ssh/github-action ~/.ssh/known_hosts

      - run: if [ "$GITHUB_REF_NAME" != "main" ]; then ssh -i $HOME/.ssh/github-action m3621@web15.biohost.net mkdir -p /home/m3621/Sites/ai-week.de/"$GITHUB_REF_NAME"; fi
      - run: rsync -rtl -e "ssh -i $HOME/.ssh/github-action" css fonts images inc js template-parts timetable *.php robots.txt m3621@web15.biohost.net:"/home/m3621/Sites/ai-week.de/${GITHUB_REF_NAME#main}/"

