name: Deploy Website

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir ~/.ssh
      - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: 'echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts'
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: chmod 400 ~/.ssh/github-action ~/.ssh/known_hosts

      - run: rsync -rtl -e "ssh -i $HOME/.ssh/github-action" *.html *.xml *.txt assets m3621@web15.biohost.net:/home/m3621/Sites/ai-week.de/

